[project]
name = "launch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic-settings>=2.11.0",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.1",
]
